version: "3"
services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    command: php -S 0.0.0.0:8000 -t public
    volumes:
      - .:/var/app
    ports: 
      - "8000:8000"
